// Public engine surface — the locked interface consumed by server, web, and simulations.
export * from './types.ts'
export { DEFAULT_RULES, normalizeRules } from './rules.ts'
export { createGame, validateDeck } from './setup.ts'
export type { CreateGameOpts } from './setup.ts'
export { applyAction } from './engine.ts'
export type { ApplyResult } from './engine.ts'
export { getLegalActions } from './legal.ts'
export { viewFor } from './view.ts'
export { validateCardSet } from './validate.ts'
export { simulateGame, simulateRandomGame } from './simulate.ts'
export type { SimOpts } from './simulate.ts'
export { POLICIES, heuristicPolicy, policyRngInit, randomPolicy } from './ai.ts'
export type { Policy, PolicyName } from './ai.ts'
export { CARD_SET } from './cards/index.ts'
export { parseCardFile, serializeCardFile, slugify, CARD_STATUSES, type CardStatus, type CardFile } from './cards/cardfile.ts'
export { PREBUILT_DECKS, buildPrebuiltDecks, deckSlugs } from './decks.ts'
export type { PrebuiltDeck } from './decks.ts'
export { influenceFor, thresholds, effPower, effHealth, effArmor, hasKw } from './helpers.ts'
