/**
 * Build the card ledger: data/cards/<color>/<slug>.md  →  packages/engine/src/cards/generated.json + data/cards/INDEX.md
 *   npm run cards          # build
 *   npm run cards:check    # validate + fail if generated files are stale (the PR gate)
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { parseCardFile, validateCardSet, type CardDef, type CardStatus } from '@newgame/engine'

const COLORS = ['red', 'yellow', 'purple'] as const
const entries: { def: CardDef; status: CardStatus }[] = []
const errors: string[] = []

for (const color of COLORS) {
  const dir = new URL(`../data/cards/${color}/`, import.meta.url)
  if (!existsSync(dir)) continue
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.md')) continue
    const res = parseCardFile(readFileSync(new URL(file, dir), 'utf8'), file.slice(0, -3), color)
    if (res.card) entries.push(res.card)
    errors.push(...res.errors)
  }
}

entries.sort((a, b) => a.def.color.localeCompare(b.def.color) || a.def.cost - b.def.cost || a.def.name.localeCompare(b.def.name))
const set = Object.fromEntries(entries.map(e => [e.def.slug, e.def]))
errors.push(...validateCardSet(set))
if (errors.length) { console.error(`✗ ${errors.length} problem(s):\n  ` + errors.join('\n  ')); process.exit(1) }

const json = JSON.stringify(set, null, 1) + '\n'
const ph = (d: CardDef) => (d.type === 'unit' ? `${d.power}/${d.health}` : '—')
const kws = (d: CardDef) => (d.kw ?? []).map(k => (k.n !== undefined ? `${k.k} ${k.n}` : k.k)).join(', ')
const row = (e: { def: CardDef; status: CardStatus }) =>
  `| [${e.def.name}](${e.def.color}/${e.def.slug}.md) | ${e.def.cost} | ${e.def.type} | ${ph(e.def)} | ${kws(e.def)} | ${e.status} | ${e.def.text.replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`
const table = (color: string) => [
  `## ${color[0].toUpperCase()}${color.slice(1)} (${entries.filter(e => e.def.color === color).length})`, '',
  '| Card | Cost | Type | P/H | Keywords | Status | Text |', '|---|---|---|---|---|---|---|',
  ...entries.filter(e => e.def.color === color).map(row), '',
].join('\n')
const counts = COLORS.map(c => `${c}: ${entries.filter(e => e.def.color === c && e.status === 'canon').length}/${entries.filter(e => e.def.color === c).length} canon`).join(' · ')
const index = `# Card Ledger Index\n\n*Generated by \`npm run cards\` — do not edit. Edit the per-card files.*\n\n**${counts}**\n\n${COLORS.map(table).join('\n')}`

const jsonUrl = new URL('../packages/engine/src/cards/generated.json', import.meta.url)
const indexUrl = new URL('../data/cards/INDEX.md', import.meta.url)
const read = (u: URL) => (existsSync(u) ? readFileSync(u, 'utf8') : '')

if (process.argv.includes('--check')) {
  if (read(jsonUrl) !== json || read(indexUrl) !== index) {
    console.error('✗ ledger valid but generated files are stale — run: npm run cards'); process.exit(1)
  }
  console.log(`✓ ${entries.length} cards valid; generated files current`)
} else {
  writeFileSync(jsonUrl, json)
  writeFileSync(indexUrl, index)
  console.log(`✓ ${entries.length} cards → generated.json + INDEX.md`)
}
