/**
 * Build the card ledger: data/cards/<color>/<slug>.md  →  packages/engine/src/cards/generated.json + data/cards/INDEX.md
 *   npm run cards          # build
 *   npm run cards:check    # validate + fail if generated files are stale (the PR gate)
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { DEFAULT_RULES, buildPrebuiltDecks, deckSlugs, parseCardFile, validateCardSet, validateDeck, type CardDef, type CardStatus } from '@newgame/engine'

const COLORS = ['red', 'yellow', 'purple'] as const
const entries: { def: CardDef; status: CardStatus }[] = []
const errors: string[] = []

for (const color of COLORS) {
  const dir = new URL(`../data/cards/${color}/`, import.meta.url)
  if (!existsSync(dir)) continue
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.md')) continue
    const res = parseCardFile(readFileSync(new URL(file, dir), 'utf8'), file.slice(0, -3), color)
    if (res.card) entries.push(res.card)
    errors.push(...res.errors)
  }
}

// deterministic ordering: fixed color rank + cost + ASCII slug (bare localeCompare follows the
// machine's ICU locale, which made the PR gate flap across systems)
const COLOR_RANK: Record<string, number> = { red: 0, yellow: 1, purple: 2 }
entries.sort((a, b) =>
  (COLOR_RANK[a.def.color] ?? 9) - (COLOR_RANK[b.def.color] ?? 9)
  || a.def.cost - b.def.cost
  || (a.def.slug < b.def.slug ? -1 : a.def.slug > b.def.slug ? 1 : 0))

const set = Object.fromEntries(entries.map(e => [e.def.slug, e.def]))
if (Object.keys(set).length !== entries.length) {
  const seen = new Set<string>()
  for (const e of entries) {
    if (seen.has(e.def.slug)) errors.push(`${e.def.slug}: duplicate slug — a card with this filename exists in more than one color directory`)
    seen.add(e.def.slug)
  }
}
errors.push(...validateCardSet(set))
// deck-legality gate: a cost edit can silently move a card in/out of a doubles rule
for (const deck of buildPrebuiltDecks(set)) {
  const slugs = deckSlugs(deck)
  if (slugs.length < DEFAULT_RULES.deckMinSize) {
    errors.push(`${deck.name}: prebuilt deck has ${slugs.length} cards, needs at least ${DEFAULT_RULES.deckMinSize} — a cost change probably moved a card out of a doubles rule (see the charter's curve section)`)
  }
  errors.push(...validateDeck(slugs, set, DEFAULT_RULES).map(e => `${deck.name}: ${e}`))
}
if (errors.length) { console.error(`✗ ${errors.length} problem(s):\n  ` + errors.join('\n  ')); process.exit(1) }

const json = JSON.stringify(set, null, 1) + '\n'
const ph = (d: CardDef) => (d.type === 'unit' ? `${d.power}/${d.health}` : '—')
const kws = (d: CardDef) => (d.kw ?? []).map(k => (k.n !== undefined ? `${k.k} ${k.n}` : k.k)).join(', ')
const row = (e: { def: CardDef; status: CardStatus }) =>
  `| [${e.def.name}](${e.def.color}/${e.def.slug}.md) | ${e.def.code ?? '—'} | ${e.def.cost} | ${e.def.type} | ${ph(e.def)} | ${kws(e.def)} | ${e.status} | ${e.def.text.replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`
const table = (color: string) => [
  `## ${color[0].toUpperCase()}${color.slice(1)} (${entries.filter(e => e.def.color === color).length})`, '',
  '| Card | Code | Cost | Type | P/H | Keywords | Status | Text |', '|---|---|---|---|---|---|---|---|',
  ...entries.filter(e => e.def.color === color).map(row), '',
].join('\n')
const counts = COLORS.map(c => `${c}: ${entries.filter(e => e.def.color === c && e.status === 'canon').length}/${entries.filter(e => e.def.color === c).length} canon`).join(' · ')
const index = `# Card Ledger Index\n\n*Generated by \`npm run cards\` — do not edit. Edit the per-card files.*\n\n**${counts}**\n\n${COLORS.map(table).join('\n')}`

const jsonUrl = new URL('../packages/engine/src/cards/generated.json', import.meta.url)
const indexUrl = new URL('../data/cards/INDEX.md', import.meta.url)
const read = (u: URL) => (existsSync(u) ? readFileSync(u, 'utf8') : '')

if (process.argv.includes('--check')) {
  if (read(jsonUrl) !== json || read(indexUrl) !== index) {
    console.error('✗ ledger valid but generated files are stale — run: npm run cards'); process.exit(1)
  }
  console.log(`✓ ${entries.length} cards valid; generated files current`)
} else {
  writeFileSync(jsonUrl, json)
  writeFileSync(indexUrl, index)
  console.log(`✓ ${entries.length} cards → generated.json + INDEX.md`)
}
